### ISSUE TITLE
Request for a Readme file

### ISSUE THREAD

**Issue by ZhenningZhou** [yimingli1998/hgc_net#1]
This is really a great work! 

Could the author add a detailed Readme file? This is important for researchers who want to learn and implement this project.

Thank you so much!

**Comment by yimingli1998** [comment]
Hi, thanks for your interest, and sorry for responding late.  I added a readme.md file and you can follow it. The code was written two years ago, and I didn't test all of them. But it should be OK. I am glad to help you if there are any other problems.
