### ISSUE TITLE
Running the 'collision_detection.py' is time-consuming

### ISSUE THREAD

**Issue by tianyuwang01** [yimingli1998/hgc_net#2]
I'm very grateful that you've open-sourced the code.

Besides, running the 'collision_detection.py' takes too much time (maybe several days on Intel-13900HX), and it may only be computable on the CPU.
Are there any solutions? Or could you provide the checkpoint weights of the model?

Again, thanks for sharing your work.

**Comment by yimingli1998** [comment]
Hi, thank you for your interest. 
The code for collision detection is based on Trimesh and it is only for CPU. We suggest running it in parallel with multiple CPU kernels. If you need it to be faster maybe you can consider using some other efficient collision detection algorithm like GJK.

**Comment by tianyuwang01** [comment]
Thank you so much for your reply!
If it is convenient, could you provide the checkpoint weights of the model?

**Comment by yimingli1998** [comment]
Yes, we can. We will let you know when it was uploaded.

**Comment by yimingli1998** [comment]
Hi, we have uploaded a pre-trained model in `model`. You can run it by `python vis.py` to visualize the generated grasps.

**Comment by tianyuwang01** [comment]
Thanks for your teams help!
